language: java
jdk:
- openjdk8
os:
- linux
sudo: required
before_install:
    - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.9-bin.tar.gz
    - tar -xzvf apache-ant-1.10.9-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.9/bin:$PATH
    - echo $(ant -version)
jobs:
  include:
  - stage: Main Build Test
    script: ant build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_KEY
  file: 
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_393LTS.tar.gz"
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_393LTS.tar.gz.MD5"
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_393LTS.zip"
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_393LTS.zip.MD5"
  skip_cleanup: true
  on:
    tags: true
