# This is a basic workflow to help you get started with Actions
# This file was contributed by Carlos Parada and Yamel Senih from ERP Consultores y Asociados, C.A

name: ADempiere Build With gradle

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
   branches: [ "master", "develop", "bugfix/*", "feature/*" ]
  pull_request:
    branches: [ "master", "develop", "bugfix/*", "feature/*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build dist application backend
  build-app:
    name: Build with gradle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: 11
          architecture: x64

#      - name: Build with Gradle
#        run: gradle build
#        env:
#          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
#          ADEMIERE_LIBRARY_VERSION: ${{ secrets.ADEMIERE_LIBRARY_VERSION }}
