# This is a basic workflow to help you get started with Actions
# This file was contributed by Carlos Parada and Yamel Senih from ERP Consultores y Asociados, C.A

name: ADempiere Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
   branches: [ "master", "develop", "bugfix/*", "feature/*" ]
  pull_request:
    branches: [ "master", "develop", "bugfix/*", "feature/*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-seed:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Ensure a compatible version of java is used
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
            java-version: '1.8'
            java-package: jdk

      # Build ADempiere with ant
      - name: Upload Seed
        uses: actions/upload-artifact@v2
        with:
            name: complete-seed
            path: build.xml
