# This is a basic workflow to help you get started with Actions
# This file was contributed by Carlos Parada and Yamel Senih from ERP Consultores y Asociados, C.A

name: ADempiere Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
   branches: [ "master", "develop", "bugfix/*", "feature/*" ]
  pull_request:
    branches: [ "master", "develop", "bugfix/*", "feature/*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Installs the latest version of Ant
      - name: Intall latest version of Ant
        run: |
          
          wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.9-bin.tar.gz
          tar -xzvf apache-ant-1.10.9-bin.tar.gz
          export ANT_HOME=`pwd`/apache-ant-1.10.9
          export PATH=${ANT_HOME}/bin:${ANT_HOME}/lib:$PATH
          echo '*************************'
          echo $ANT_HOME
          echo $PATH
          echo $(ant -version)
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Build ADempiere with ant
      - name: Build Adempiere ...
        run: |
           echo $GITHUB_REF
           echo $GITHUB_HEAD_REF
           echo $GITHUB_BASE_REF
           echo ${{ github.ref }}
           cd utils_dev
           ant complete
