name: Action for generate SEED aplying all XMLs
on: push

jobs:
  # Label of the container job
  create-seed:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check version of PostgreSQL client
        run: psql --version
      - name: Install ant 
      - run: |
          echo $GITHUB_REF
          echo $GITHUB_HEAD_REF
          echo $GITHUB_BASE_REF
          echo ${{ github.ref }}
          echo "Current ant version: $(ant -version)"
          echo "Installing ant version 1.10.9"
          wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.9-bin.tar.gz
          tar -xzf apache-ant-1.10.9-bin.tar.gz
          export ANT_HOME=`pwd`/apache-ant-1.10.9
          export PATH=${ANT_HOME}/bin:$PATH
          echo $ANT_HOME
          echo $PATH
          echo $(ant -version)
      - name: Build Complete and Apply XML
      - run: ant build
